default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sailhero-api_development

test:
  <<: *default
  database: sailhero_api_test

production:
  <<: *default
  database: sailhero-api_production
  username: sailhero-api
  password: <%= ENV['SAILHERO-API_DATABASE_PASSWORD'] %>
